In [126]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [127]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [128]:
df.shape

(569, 33)

In [129]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [130]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

## Train Test split

In [131]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

#### scaling

In [132]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [133]:
X_train

array([[ 1.37932149,  1.29678258,  1.22862499, ...,  1.23982579,
         1.74100839,  0.5031957 ],
       [-0.3558377 ,  0.09398348, -0.38308947, ..., -0.79079031,
         0.67643679, -0.38379582],
       [ 1.62478303,  0.26547167,  1.57694873, ...,  0.71121215,
        -0.58846632,  0.41638133],
       ...,
       [-0.52512152, -0.29186494, -0.55766114, ..., -0.30563704,
         0.91153659, -0.86298827],
       [ 1.83638781, -0.42762642,  1.75315957, ...,  1.48024481,
        -0.35667779, -0.77217588],
       [ 0.37490414,  0.0796928 ,  0.39674593, ...,  0.55863854,
        -0.1116442 , -0.22159003]])

In [134]:
y_train

87     M
436    B
517    M
144    B
141    M
      ..
317    M
283    M
409    B
373    M
131    M
Name: diagnosis, Length: 455, dtype: object

## Label Encoding

In [135]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

# Numpy arrays to PyTorch tensors

In [136]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [137]:
X_train_tensor.shape

torch.Size([455, 30])

In [138]:
y_train_tensor.shape

torch.Size([455])

## Defining the model

In [139]:
class MysimpleNN():
    def __init__(self,X):
        self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
        self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)
    def forward(self,X):
        z=torch.matmul(X,self.weights)+self.bias
        y_pred=torch.sigmoid(z)
        return y_pred
    def loss_function(self,y_pred,y):
        #clamp
        epsilon=1e-7
        y_pred=torch.clamp(y_pred,epsilon,1-epsilon)
        
        loss=-(y_train_tensor*torch.log(y_pred)+(1-y_train_tensor)*torch.log(1-y_pred)).mean()
        return loss

## Important Parameters

In [140]:
learning_rate = 0.1
epochs = 25

## Training Pipeline

In [141]:
# create model
model = MysimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.9903118591554065
Epoch: 2, Loss: 3.8809268182876404
Epoch: 3, Loss: 3.7695628024049443
Epoch: 4, Loss: 3.6541309687036914
Epoch: 5, Loss: 3.534238948632928
Epoch: 6, Loss: 3.407092691584361
Epoch: 7, Loss: 3.277009673408188
Epoch: 8, Loss: 3.146012015622666
Epoch: 9, Loss: 3.0089365186680257
Epoch: 10, Loss: 2.8707405045797043
Epoch: 11, Loss: 2.729293137541823
Epoch: 12, Loss: 2.5851355760668597
Epoch: 13, Loss: 2.4343015233860736
Epoch: 14, Loss: 2.2766281892463756
Epoch: 15, Loss: 2.117769364520374
Epoch: 16, Loss: 1.9629764203247715
Epoch: 17, Loss: 1.8091264310626556
Epoch: 18, Loss: 1.663585849427114
Epoch: 19, Loss: 1.523789667191536
Epoch: 20, Loss: 1.3881293817730442
Epoch: 21, Loss: 1.2666707043675345
Epoch: 22, Loss: 1.160883678614224
Epoch: 23, Loss: 1.0716361860526926
Epoch: 24, Loss: 0.9988850927824939
Epoch: 25, Loss: 0.9415233384464103

In [142]:
model.bias

tensor([-0.0850], dtype=torch.float64, requires_grad=True)

In [143]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6246537566184998

In [144]:
y_pred

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])